- repo: https://github.com/DevSecOps-AppSec/pre-commit-hooks
  rev: v8.18.1
  hooks:
    - id: check-file-size
      name: Check File Size
      entry: check_file_size.py
      language: python
      types: [file]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
