- repo: https://github.com/DevSecOps-AppSec/pre-commit-hooks
  rev: main  # Use the version you want
  hooks:
    - id: check-file-size
      name: Check File Size
      entry: check_file_size.py
      language: python
      types: [python]
